# Generated by Django 4.0.5 on 2022-07-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hope', '0002_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_books',
            name='return_status',
            field=models.CharField(default='booked', max_length=15),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowed_books',
            name='pickup_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='borrowed_books',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
