# Generated by Django 4.0.5 on 2022-07-10 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hope', '0004_alter_books_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed_books',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='hope.books'),
        ),
    ]
